"""`alerts` (SPEC 3.22): generated by the rule engine, deduplicated by fingerprint (SPEC 7.1)."""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, IdMixin, TimestampMixin, enum_check

ALERT_SEVERITIES = ("info", "warning", "critical")
ALERT_STATUSES = ("open", "acknowledged", "resolved", "suppressed")
ALERT_TYPES = (
    "GUARANTEE_EXPIRING",
    "ADVANCE_GUARANTEE_SHORT",
    "GUARANTEE_MISSING",
    "CONTRACT_ENDING",
    "STAGE_DELAYED",
    "PROGRESS_BEHIND",
    "ISSUE_SLA",
    "DOC_MISSING",
    "DAILY_LOG_MISSING",
    "REPORT_DUE",
    "CROSS_PKG_DEPENDENCY",
    "PAYMENT_DUE",
    "PLAN_STEP_OVERDUE",
    # software-delivery projects
    "TASK_LATE",
    "MILESTONE_SOON",
    "WEEKLY_REPORT_MISSING",
    "DECISION_OVERDUE",
    "RISK_VERY_HIGH",
)


class Alert(IdMixin, TimestampMixin, Base):
    __tablename__ = "alerts"
    __table_args__ = (
        enum_check("severity", ALERT_SEVERITIES),
        enum_check("status", ALERT_STATUSES),
        enum_check("alert_type", ALERT_TYPES),
        Index("ix_alerts_status", "status"),
        Index("ix_alerts_package", "package_id"),
        Index("ix_alerts_project", "project_id"),
    )

    alert_type: Mapped[str] = mapped_column(String(40), nullable=False)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(40), nullable=False)
    entity_id: Mapped[str] = mapped_column(String(64), nullable=False)
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False
    )
    package_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("packages.id"), nullable=True
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="open", nullable=False)
    assigned_to: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    # rule_code + entity_id + level (SPEC 7.1): the same condition never creates two alerts.
    fingerprint: Mapped[str] = mapped_column(String(200), unique=True, nullable=False)
    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    snoozed_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    snooze_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    # When the immediate e-mail for a critical alert went out (SPEC 4.10): never sent twice.
    notified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
