"""projects packages contracts

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 14:13:29.935297

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column("tax_code", sa.String(length=30), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("representative", sa.String(length=200), nullable=True),
        sa.Column("position", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("bank_account", sa.String(length=50), nullable=True),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column("org_type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "org_type IN ('investor','consultant','contractor','supervisor','auditor','beneficiary','bank','other')",
            name=op.f("ck_organizations_org_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "projects",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("investor_org_id", sa.UUID(), nullable=True),
        sa.Column("decision_maker", sa.Text(), nullable=True),
        sa.Column("total_investment", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("funding_source", sa.Text(), nullable=True),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("treasury_account", sa.String(length=50), nullable=True),
        sa.Column("project_code_kbnn", sa.String(length=30), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["investor_org_id"],
            ["organizations.id"],
            name=op.f("fk_projects_investor_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("code", name=op.f("uq_projects_code")),
    )
    op.create_table(
        "packages",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("scope_summary", sa.Text(), nullable=True),
        sa.Column("package_type", sa.String(length=20), nullable=False),
        sa.Column("package_price", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("selection_form", sa.String(length=30), nullable=True),
        sa.Column("selection_method", sa.String(length=30), nullable=True),
        sa.Column("approved_duration_days", sa.Integer(), nullable=True),
        sa.Column("etbmt_no", sa.String(length=50), nullable=True),
        sa.Column("kh_lcnt_decision", sa.Text(), nullable=True),
        sa.Column("approval_decision", sa.Text(), nullable=True),
        sa.Column("winning_price", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("winning_org_text", sa.Text(), nullable=True),
        sa.Column("current_stage", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("health", sa.String(length=10), nullable=False),
        sa.Column("health_reason", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "current_stage IN ('S1_START','S2_SELECTION','S3_EXECUTION','S4_ACCEPTANCE','S5_PAYMENT_SETTLEMENT')",
            name=op.f("ck_packages_current_stage"),
        ),
        sa.CheckConstraint(
            "health IN ('green','amber','red','grey')", name=op.f("ck_packages_health")
        ),
        sa.CheckConstraint(
            "package_type IN ('goods','consulting')", name=op.f("ck_packages_package_type")
        ),
        sa.CheckConstraint(
            "selection_form IN ('open_tender','direct_appointment_short')",
            name=op.f("ck_packages_selection_form"),
        ),
        sa.CheckConstraint(
            "selection_method IN ('one_stage_one_envelope','one_stage_two_envelope','short_procedure')",
            name=op.f("ck_packages_selection_method"),
        ),
        sa.CheckConstraint(
            "status IN ('planning','bidding','negotiating','contract_signed','executing','accepted','settled','cancelled')",
            name=op.f("ck_packages_status"),
        ),
        sa.CheckConstraint("number BETWEEN 1 AND 99", name=op.f("ck_packages_number_range")),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_packages_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("project_id", "number", name="project_number"),
    )
    op.create_table(
        "contracts",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("contract_no", sa.String(length=50), nullable=False),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("planned_end_date", sa.Date(), nullable=True),
        sa.Column("extended_end_date", sa.Date(), nullable=True),
        sa.Column("end_date_override", sa.Boolean(), nullable=False),
        sa.Column("contract_type", sa.String(length=20), nullable=True),
        sa.Column("price_adjustment", sa.Boolean(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("advance_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("advance_amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("advance_recovery_note", sa.Text(), nullable=True),
        sa.Column("performance_bond_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("performance_bond_amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("warranty_bond_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("warranty_bond_amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("penalty_rate_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("penalty_unit", sa.String(length=10), nullable=True),
        sa.Column("penalty_cap_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("payment_terms_text", sa.Text(), nullable=True),
        sa.Column("payment_term_days", sa.Integer(), nullable=True),
        sa.Column("copies_text", sa.Text(), nullable=True),
        sa.Column("investor_signer", sa.String(length=200), nullable=True),
        sa.Column("investor_account", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_doc_id", sa.UUID(), nullable=True),
        sa.Column("data_quality_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "contract_type IN ('lump_sum','unit_price')", name=op.f("ck_contracts_contract_type")
        ),
        sa.CheckConstraint(
            "penalty_unit IN ('day','week')", name=op.f("ck_contracts_penalty_unit")
        ),
        sa.CheckConstraint(
            "status IN ('draft','signed','executing','accepted','liquidated','terminated')",
            name=op.f("ck_contracts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_contracts_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
    )
    op.create_table(
        "contract_amendments",
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("amendment_no", sa.String(length=50), nullable=False),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("new_end_date", sa.Date(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "type IN ('duration','value','scope','other')", name=op.f("ck_contract_amendments_type")
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_amendments_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_amendments")),
    )
    op.create_table(
        "contract_items",
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("member_org_id", sa.UUID(), nullable=True),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("warranty_months", sa.Integer(), nullable=True),
        sa.Column("requires_calibration", sa.Boolean(), nullable=False),
        sa.Column("origin", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_items_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_org_id"],
            ["organizations.id"],
            name=op.f("fk_contract_items_member_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_items")),
    )
    op.create_table(
        "contract_parties",
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("share_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("share_amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("advance_amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("bank_account", sa.String(length=50), nullable=True),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "role IN ('lead','member','sole')", name=op.f("ck_contract_parties_role")
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_parties_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_contract_parties_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_parties")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract_parties")
    op.drop_table("contract_items")
    op.drop_table("contract_amendments")
    op.drop_table("contracts")
    op.drop_table("packages")
    op.drop_table("projects")
    op.drop_table("organizations")
    # ### end Alembic commands ###
