"""guarantees payments disbursement

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 14:28:34.499209

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disbursement_plan",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("planned_amount", sa.Numeric(precision=18, scale=0), nullable=False),
        sa.Column("actual_amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name=op.f("ck_disbursement_plan_month_range")),
        sa.CheckConstraint(
            "year BETWEEN 2000 AND 2100", name=op.f("ck_disbursement_plan_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_disbursement_plan_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_disbursement_plan_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disbursement_plan")),
    )
    op.create_table(
        "guarantees",
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("provider_org_id", sa.UUID(), nullable=True),
        sa.Column("guarantee_type", sa.String(length=20), nullable=False),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column("guarantee_no", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=0), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("validity_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verify_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "guarantee_type IN ('bid','performance','advance','warranty')",
            name=op.f("ck_guarantees_guarantee_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','valid','expiring','expired','released','missing')",
            name=op.f("ck_guarantees_status"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_guarantees_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_org_id"],
            ["organizations.id"],
            name=op.f("fk_guarantees_provider_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guarantees")),
    )
    op.create_table(
        "payments",
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("payment_type", sa.String(length=20), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=0), nullable=False),
        sa.Column("requested_date", sa.Date(), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("invoice_no", sa.String(length=100), nullable=True),
        sa.Column("treasury_ref", sa.String(length=100), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "payment_type IN ('advance','payment','recovery','penalty')",
            name=op.f("ck_payments_payment_type"),
        ),
        sa.CheckConstraint(
            "status IN ('planned','requested','approved','paid','rejected')",
            name=op.f("ck_payments_status"),
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_payments_seq_nonneg")),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_payments_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_payments_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("guarantees")
    op.drop_table("disbursement_plan")
    # ### end Alembic commands ###
