"""documents checklists access

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 14:41:15.274362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Vietnamese search without diacritics (SPEC 2.3, section 9).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_templates",
        sa.Column("package_type", sa.String(length=20), nullable=False),
        sa.Column("stage_code", sa.String(length=30), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("due_offset_days", sa.Integer(), nullable=True),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_templates")),
        sa.UniqueConstraint("package_type", "stage_code", "doc_type", "title", name="key"),
    )
    op.create_table(
        "package_access",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_package_access_package_id_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_package_access_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_access")),
        sa.UniqueConstraint("user_id", "package_id", name="user_package"),
    )
    op.create_table(
        "documents",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("contract_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("doc_no", sa.String(length=100), nullable=True),
        sa.Column("doc_date", sa.Date(), nullable=True),
        sa.Column("issuer", sa.String(length=300), nullable=True),
        sa.Column("confidentiality", sa.String(length=20), nullable=False),
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=150), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_document_id", sa.UUID(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("text_extracted", sa.Boolean(), nullable=False),
        sa.Column("extraction_status", sa.String(length=20), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('legal','selection','contract','execution','acceptance','payment','other')",
            name=op.f("ck_documents_category"),
        ),
        sa.CheckConstraint(
            "confidentiality IN ('normal','sensitive')", name=op.f("ck_documents_confidentiality")
        ),
        sa.CheckConstraint(
            "extraction_status IN ('pending','done','needs_ocr','unsupported','failed')",
            name=op.f("ck_documents_extraction_status"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contracts.id"], name=op.f("fk_documents_contract_id_contracts")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_documents_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["parent_document_id"],
            ["documents.id"],
            name=op.f("fk_documents_parent_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_documents_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_documents_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        "ix_documents_package_current", "documents", ["package_id", "is_current"], unique=False
    )
    op.create_index(
        "ix_documents_search_vector",
        "documents",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_documents_title_trgm",
        "documents",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_documents_package_sha256",
        "documents",
        ["package_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND package_id IS NOT NULL"),
    )
    op.create_table(
        "checklist_items",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("stage_code", sa.String(length=30), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('missing','received','not_applicable')",
            name=op.f("ck_checklist_items_status"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_checklist_items_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_checklist_items_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["checklist_templates.id"],
            name=op.f("fk_checklist_items_template_id_checklist_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_items")),
        sa.UniqueConstraint("package_id", "template_id", name="package_template"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checklist_items")
    op.drop_index(
        "uq_documents_package_sha256",
        table_name="documents",
        postgresql_where=sa.text("deleted_at IS NULL AND package_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_documents_title_trgm",
        table_name="documents",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index("ix_documents_search_vector", table_name="documents", postgresql_using="gin")
    op.drop_index("ix_documents_package_current", table_name="documents")
    op.drop_table("documents")
    op.drop_table("package_access")
    op.drop_table("checklist_templates")
    # ### end Alembic commands ###
