"""stages tasks progress logs

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 15:07:59.727713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progress_logs",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("progress_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("issues", sa.Text(), nullable=True),
        sa.Column("next_steps", sa.Text(), nullable=True),
        sa.Column("workers", sa.Integer(), nullable=True),
        sa.Column("weather", sa.String(length=100), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column(
            "attachments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "progress_pct BETWEEN 0 AND 100", name=op.f("ck_progress_logs_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_progress_logs_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_progress_logs_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_logs")),
        sa.UniqueConstraint("package_id", "log_date", "author_id", name="package_date_author"),
    )
    op.create_index(
        "uq_progress_logs_client_id",
        "progress_logs",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("client_id IS NOT NULL"),
    )
    op.create_table(
        "stage_plans",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("stage_code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_end", sa.Date(), nullable=True),
        sa.Column("actual_start", sa.Date(), nullable=True),
        sa.Column("actual_end", sa.Date(), nullable=True),
        sa.Column("progress_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "stage_code IN ('S1_START','S2_SELECTION','S3_EXECUTION','S4_ACCEPTANCE','S5_PAYMENT_SETTLEMENT')",
            name=op.f("ck_stage_plans_stage_code"),
        ),
        sa.CheckConstraint(
            "status IN ('not_started','in_progress','done','delayed','blocked')",
            name=op.f("ck_stage_plans_status"),
        ),
        sa.CheckConstraint(
            "progress_pct BETWEEN 0 AND 100", name=op.f("ck_stage_plans_progress_range")
        ),
        sa.CheckConstraint("weight >= 0", name=op.f("ck_stage_plans_weight_nonneg")),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_stage_plans_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_plans")),
        sa.UniqueConstraint("package_id", "stage_code", name="package_stage"),
    )
    op.create_table(
        "tasks",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("stage_plan_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_end", sa.Date(), nullable=True),
        sa.Column("actual_end", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("depends_on", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("priority IN ('low','normal','high')", name=op.f("ck_tasks_priority")),
        sa.CheckConstraint(
            "status IN ('todo','doing','done','blocked')", name=op.f("ck_tasks_status")
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.id"], name=op.f("fk_tasks_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_tasks_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["stage_plan_id"], ["stage_plans.id"], name=op.f("fk_tasks_stage_plan_id_stage_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_package", "tasks", ["package_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_package", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("stage_plans")
    op.drop_index(
        "uq_progress_logs_client_id",
        table_name="progress_logs",
        postgresql_where=sa.text("client_id IS NOT NULL"),
    )
    op.drop_table("progress_logs")
    # ### end Alembic commands ###
