"""risks issues meetings changes

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-06 15:30:29.792029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("day", name=op.f("uq_holidays_day")),
    )
    op.create_table(
        "issues",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("issue_type", sa.String(length=30), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reported_by", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column(
            "reported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("decision_doc_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "issue_type IN ('operational','contract','schedule','investor_request','other')",
            name=op.f("ck_issues_issue_type"),
        ),
        sa.CheckConstraint(
            "status IN ('open','in_progress','escalated','resolved','closed')",
            name=op.f("ck_issues_status"),
        ),
        sa.CheckConstraint("level IN (1, 2, 3)", name=op.f("ck_issues_level_range")),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_issues_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_issues_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["reported_by"], ["users.id"], name=op.f("fk_issues_reported_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint("code", name=op.f("uq_issues_code")),
    )
    op.create_index("ix_issues_package", "issues", ["package_id"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("meeting_type", sa.String(length=30), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("chair", sa.String(length=200), nullable=True),
        sa.Column(
            "attendees",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("minutes", sa.Text(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "meeting_type IN ('kickoff','package_kickoff','weekly','issue_resolution','other')",
            name=op.f("ck_meetings_meeting_type"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_meetings_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_meetings_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.create_table(
        "risks",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("mitigation", sa.Text(), nullable=True),
        sa.Column("contingency", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "category IN ('schedule','cost','quality','legal','contract','supply','safety','other')",
            name=op.f("ck_risks_category"),
        ),
        sa.CheckConstraint(
            "source IN ('de_cuong','analysis','manual')", name=op.f("ck_risks_source")
        ),
        sa.CheckConstraint(
            "status IN ('open','mitigating','occurred','closed')", name=op.f("ck_risks_status")
        ),
        sa.CheckConstraint("impact BETWEEN 1 AND 5", name=op.f("ck_risks_impact_range")),
        sa.CheckConstraint("probability BETWEEN 1 AND 5", name=op.f("ck_risks_probability_range")),
        sa.CheckConstraint("score = probability * impact", name=op.f("ck_risks_score_matches")),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_risks_owner_id_users")),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_risks_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_risks_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risks")),
        sa.UniqueConstraint("code", name=op.f("uq_risks_code")),
    )
    op.create_index("ix_risks_package", "risks", ["package_id"], unique=False)
    op.create_table(
        "action_items",
        sa.Column("meeting_id", sa.UUID(), nullable=True),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open','done','cancelled')", name=op.f("ck_action_items_status")
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_action_items_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_action_items_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_action_items_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_items")),
    )
    op.create_table(
        "issue_events",
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event", sa.String(length=20), nullable=False),
        sa.Column("from_level", sa.Integer(), nullable=True),
        sa.Column("to_level", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "event IN ('created','escalated','resolved','reopened','closed','due_changed','assigned','status_changed')",
            name=op.f("ck_issue_events_event"),
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_events_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_issue_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_events")),
    )
    op.create_index("ix_issue_events_issue", "issue_events", ["issue_id"], unique=False)
    op.create_table(
        "change_requests",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("proposed_by_org_id", sa.UUID(), nullable=True),
        sa.Column("supervisor_opinion", sa.Text(), nullable=True),
        sa.Column("tvqlda_opinion", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("amendment_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "change_type IN ('model','origin','allocation','schedule','other')",
            name=op.f("ck_change_requests_change_type"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed','reviewing','approved','rejected','appendix_signed')",
            name=op.f("ck_change_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["amendment_id"],
            ["contract_amendments.id"],
            name=op.f("fk_change_requests_amendment_id_contract_amendments"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_change_requests_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_change_requests_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_org_id"],
            ["organizations.id"],
            name=op.f("fk_change_requests_proposed_by_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_requests")),
        sa.UniqueConstraint("code", name=op.f("uq_change_requests_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("change_requests")
    op.drop_index("ix_issue_events_issue", table_name="issue_events")
    op.drop_table("issue_events")
    op.drop_table("action_items")
    op.drop_index("ix_risks_package", table_name="risks")
    op.drop_table("risks")
    op.drop_table("meetings")
    op.drop_index("ix_issues_package", table_name="issues")
    op.drop_table("issues")
    op.drop_table("holidays")
    # ### end Alembic commands ###
