"""alerts consulting role payment due

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-06 15:52:34.464755

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("alert_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("fingerprint", sa.String(length=200), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snooze_reason", sa.Text(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "alert_type IN ('GUARANTEE_EXPIRING','ADVANCE_GUARANTEE_SHORT','GUARANTEE_MISSING','CONTRACT_ENDING','STAGE_DELAYED','PROGRESS_BEHIND','ISSUE_SLA','DOC_MISSING','DAILY_LOG_MISSING','REPORT_DUE','CROSS_PKG_DEPENDENCY','PAYMENT_DUE')",
            name=op.f("ck_alerts_alert_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('info','warning','critical')", name=op.f("ck_alerts_severity")
        ),
        sa.CheckConstraint(
            "status IN ('open','acknowledged','resolved','suppressed')",
            name=op.f("ck_alerts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"], ["users.id"], name=op.f("fk_alerts_acknowledged_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_alerts_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_alerts_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_alerts_fingerprint")),
    )
    op.create_index("ix_alerts_package", "alerts", ["package_id"], unique=False)
    op.create_index("ix_alerts_status", "alerts", ["status"], unique=False)
    op.add_column("packages", sa.Column("consulting_role", sa.String(length=10), nullable=True))
    op.create_check_constraint(
        op.f("ck_packages_consulting_role"),
        "packages",
        "consulting_role IN ('tvqlda','tvgs','other')",
    )
    op.add_column("payments", sa.Column("due_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "due_date")
    op.drop_constraint(op.f("ck_packages_consulting_role"), "packages", type_="check")
    op.drop_column("packages", "consulting_role")
    op.drop_index("ix_alerts_status", table_name="alerts")
    op.drop_index("ix_alerts_package", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
