"""outgoing doc numbers

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-06 23:44:04.555801

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outgoing_doc_numbers",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("doc_kind", sa.String(length=10), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("doc_no", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("issued_date", sa.Date(), nullable=False),
        sa.Column("created_by_name", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "doc_kind IN ('CV','BC','TB','BB','QD','TT','KH')",
            name=op.f("ck_outgoing_doc_numbers_doc_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outgoing_doc_numbers")),
        sa.UniqueConstraint("year", "doc_kind", "seq", name="year_kind_seq"),
    )
    op.create_index("ix_outgoing_doc_numbers_year", "outgoing_doc_numbers", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outgoing_doc_numbers_year", table_name="outgoing_doc_numbers")
    op.drop_table("outgoing_doc_numbers")
    # ### end Alembic commands ###
