"""package plans

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-07 14:10:20.537376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # a new alert type: widen the CHECK of the alerts table
    op.drop_constraint(op.f("ck_alerts_alert_type"), "alerts", type_="check")
    op.create_check_constraint(
        op.f("ck_alerts_alert_type"),
        "alerts",
        "alert_type IN ('GUARANTEE_EXPIRING','ADVANCE_GUARANTEE_SHORT','GUARANTEE_MISSING','CONTRACT_ENDING','STAGE_DELAYED','PROGRESS_BEHIND','ISSUE_SLA','DOC_MISSING','DAILY_LOG_MISSING','REPORT_DUE','CROSS_PKG_DEPENDENCY','PAYMENT_DUE','PLAN_STEP_OVERDUE')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_plans",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("addressee", sa.Text(), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("contract_text", sa.Text(), nullable=True),
        sa.Column("contract_start", sa.Date(), nullable=True),
        sa.Column("contract_end", sa.Date(), nullable=True),
        sa.Column("implement_text", sa.Text(), nullable=True),
        sa.Column("implement_start", sa.Date(), nullable=True),
        sa.Column("implement_end", sa.Date(), nullable=True),
        sa.Column(
            "locations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("signer", sa.Text(), nullable=True),
        sa.Column("declared_total", sa.Integer(), nullable=True),
        sa.Column("source_file_name", sa.String(length=255), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["imported_by"], ["users.id"], name=op.f("fk_package_plans_imported_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_package_plans_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_plans")),
        sa.UniqueConstraint("package_id", name=op.f("uq_package_plans_package_id")),
    )
    op.create_table(
        "plan_items",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column(
            "assignments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["package_plans.id"],
            name=op.f("fk_plan_items_plan_id_package_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_items")),
    )
    op.create_index("ix_plan_items_plan", "plan_items", ["plan_id"], unique=False)
    op.create_table(
        "plan_steps",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("group_no", sa.Integer(), nullable=True),
        sa.Column("group_title", sa.Text(), nullable=True),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=40), nullable=False),
        sa.Column("time_text", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("estimated", sa.Boolean(), nullable=False),
        sa.Column("time_note", sa.Text(), nullable=True),
        sa.Column(
            "participants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actual_start", sa.Date(), nullable=True),
        sa.Column("actual_end", sa.Date(), nullable=True),
        sa.Column("tracking_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('not_started','in_progress','done','blocked')",
            name=op.f("ck_plan_steps_status"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["package_plans.id"],
            name=op.f("fk_plan_steps_plan_id_package_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_steps")),
    )
    op.create_index("ix_plan_steps_plan", "plan_steps", ["plan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM alerts WHERE alert_type = 'PLAN_STEP_OVERDUE'")
    op.drop_constraint(op.f("ck_alerts_alert_type"), "alerts", type_="check")
    op.create_check_constraint(
        op.f("ck_alerts_alert_type"),
        "alerts",
        "alert_type IN ('GUARANTEE_EXPIRING','ADVANCE_GUARANTEE_SHORT','GUARANTEE_MISSING','CONTRACT_ENDING','STAGE_DELAYED','PROGRESS_BEHIND','ISSUE_SLA','DOC_MISSING','DAILY_LOG_MISSING','REPORT_DUE','CROSS_PKG_DEPENDENCY','PAYMENT_DUE')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plan_steps_plan", table_name="plan_steps")
    op.drop_table("plan_steps")
    op.drop_index("ix_plan_items_plan", table_name="plan_items")
    op.drop_table("plan_items")
    op.drop_table("package_plans")
    # ### end Alembic commands ###
